// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

// Genres
export const LOAD_GENRES_REQUEST = 'LOAD_GENRES_REQUEST'
export const LOAD_GENRES_SUCCESS = 'LOAD_GENRES_SUCCESS'
export const LOAD_GENRES_FAILURE = 'LOAD_GENRES_FAILURE'

// Single Genre
export const LOAD_GENRE_REQUEST = 'LOAD_GENRE_REQUEST'
export const LOAD_GENRE_SUCCESS = 'LOAD_GENRE_SUCCESS'
export const LOAD_GENRE_FAILURE = 'LOAD_GENRE_FAILURE'

// Films
export const LOAD_FILMS_REQUEST = 'LOAD_FILMS_REQUEST'
export const LOAD_FILMS_SUCCESS = 'LOAD_FILMS_SUCCESS'
export const LOAD_FILMS_FAILURE = 'LOAD_FILMS_FAILURE'

// Single Film
export const LOAD_FILM_REQUEST = 'LOAD_FILM_REQUEST'
export const LOAD_FILM_SUCCESS = 'LOAD_FILM_SUCCESS'
export const LOAD_FILM_FAILURE = 'LOAD_FILM_FAILURE'

// Single Film Credits
export const LOAD_FILM_CREDITS_REQUEST = 'LOAD_FILM_CREDITS_REQUEST'
export const LOAD_FILM_CREDITS_SUCCESS = 'LOAD_FILM_CREDITS_SUCCESS'
export const LOAD_FILM_CREDITS_FAILURE = 'LOAD_FILM_CREDITS_FAILURE'

