// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

// Genres
export const LOAD_GENRES_REQUEST = 'LOAD_GENRES_REQUEST'
export const LOAD_GENRES_SUCCESS = 'LOAD_GENRES_SUCCESS'
export const LOAD_GENRES_FAILURE = 'LOAD_GENRES_FAILURE'

// Single Genre
export const LOAD_GENRE_FILMS_REQUEST = 'LOAD_GENRE_FILMS_REQUEST'
export const LOAD_GENRE_FILMS_SUCCESS = 'LOAD_GENRE_FILMS_SUCCESS'
export const LOAD_GENRE_FILMS_FAILURE = 'LOAD_GENRE_FILMS_FAILURE'

// Single Genre
export const LOAD_GENRE_REQUEST = 'LOAD_GENRE_REQUEST'
export const LOAD_GENRE_SUCCESS = 'LOAD_GENRE_SUCCESS'
export const LOAD_GENRE_FAILURE = 'LOAD_GENRE_FAILURE'

// Genre Description Save
export const SAVE_GENRE_DESCRIPTION_REQUEST = 'SAVE_GENRE_DESCRIPTION_REQUEST'
export const SAVE_GENRE_DESCRIPTION_SUCCESS = 'SAVE_GENRE_DESCRIPTION_SUCCESS'
export const SAVE_GENRE_DESCRIPTION_FAILURE = 'SAVE_GENRE_DESCRIPTION_FAILURE'

// Genre Descriptions Load
export const LOAD_GENRE_DESCRIPTIONS_REQUEST = 'LOAD_GENRE_DESCRIPTIONS_REQUEST'
export const LOAD_GENRE_DESCRIPTIONS_SUCCESS = 'LOAD_GENRE_DESCRIPTIONS_SUCCESS'
export const LOAD_GENRE_DESCRIPTIONS_FAILURE = 'LOAD_GENRE_DESCRIPTIONS_FAILURE'

// Films
export const LOAD_FILMS_REQUEST = 'LOAD_FILMS_REQUEST'
export const LOAD_FILMS_SUCCESS = 'LOAD_FILMS_SUCCESS'
export const LOAD_FILMS_FAILURE = 'LOAD_FILMS_FAILURE'

// Single Film
export const LOAD_FILM_REQUEST = 'LOAD_FILM_REQUEST'
export const LOAD_FILM_SUCCESS = 'LOAD_FILM_SUCCESS'
export const LOAD_FILM_FAILURE = 'LOAD_FILM_FAILURE'

// Single Film Credits
export const LOAD_FILM_CREDITS_REQUEST = 'LOAD_FILM_CREDITS_REQUEST'
export const LOAD_FILM_CREDITS_SUCCESS = 'LOAD_FILM_CREDITS_SUCCESS'
export const LOAD_FILM_CREDITS_FAILURE = 'LOAD_FILM_CREDITS_FAILURE'

// Popular Films
export const FETCH_POPULAR_REQUEST = 'FETCH_POPULAR_REQUEST'
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS'
export const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE'

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// Save User
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST'
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS'
export const SAVE_USER_FAILURE = 'SAVE_USER_FAILURE'

// Auth Messages
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE'
export const DELETE_AUTHORIZATION = 'DELETE_AUTHORIZATION'
